[package]
name = "crossterm-play"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.28"
clap_derive = "4.5.28"
crossterm = "0.28.1"
rand = "0.9.0"
tokio = { version = "1.43.0", features = ["full"] }
